-- ─────────────────────────────────────────────────────────────────────────────
-- UX Brief · Supabase schema
-- Run this in your Supabase SQL editor (Dashboard → SQL Editor → New query)
-- ─────────────────────────────────────────────────────────────────────────────

-- Enable UUID generation
create extension if not exists "pgcrypto";

-- ─── Sessions ────────────────────────────────────────────────────────────────
-- One session = one design brief exercise (e.g. "Wisewell US Homepage v1")

create table sessions (
  id                        uuid primary key default gen_random_uuid(),
  project_name              text not null,
  created_by                text not null,                        -- admin name / email
  status                    text not null default 'collecting'    -- collecting | ready_to_diff | diffed | exported_to_figma
                              check (status in ('collecting','ready_to_diff','diffed','exported_to_figma')),
  min_respondents_for_diff  int  not null default 2,
  figma_file_key            text,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);

-- ─── Respondents ─────────────────────────────────────────────────────────────
-- One row per stakeholder submission

create table respondents (
  id            uuid primary key default gen_random_uuid(),
  session_id    uuid not null references sessions(id) on delete cascade,
  name          text not null,
  role          text not null,
  layer         text not null,
  answers       jsonb not null default '{}',
  submitted_at  timestamptz not null default now()
);

-- ─── Concepts ────────────────────────────────────────────────────────────────
-- One concept per respondent, generated by Claude after submission

create table concepts (
  id              uuid primary key default gen_random_uuid(),
  respondent_id   uuid not null unique references respondents(id) on delete cascade,
  session_id      uuid not null references sessions(id) on delete cascade,
  concept_json    jsonb not null,               -- structured Concept object
  raw_text        text not null,                -- Claude's raw output for debugging
  figma_node_id   text,                         -- populated after Figma export
  generated_at    timestamptz not null default now()
);

-- ─── Diffs ───────────────────────────────────────────────────────────────────
-- One diff per session, regenerated each time a new concept is added

create table diffs (
  id            uuid primary key default gen_random_uuid(),
  session_id    uuid not null references sessions(id) on delete cascade,
  items         jsonb not null default '[]',    -- DiffItem[]
  raw_text      text not null,
  generated_at  timestamptz not null default now()
);

-- Only keep the latest diff per session
create unique index diffs_session_id_idx on diffs(session_id);

-- ─── Magic link tokens ───────────────────────────────────────────────────────
-- Shareable links for stakeholders — no password required

create table invite_tokens (
  id          uuid primary key default gen_random_uuid(),
  session_id  uuid not null references sessions(id) on delete cascade,
  email       text not null,
  token       text not null unique default encode(gen_random_bytes(32), 'hex'),
  used        boolean not null default false,
  expires_at  timestamptz not null default (now() + interval '7 days'),
  created_at  timestamptz not null default now()
);

-- ─── Indexes ─────────────────────────────────────────────────────────────────

create index respondents_session_id_idx  on respondents(session_id);
create index concepts_session_id_idx     on concepts(session_id);
create index invite_tokens_token_idx     on invite_tokens(token);
create index invite_tokens_session_idx   on invite_tokens(session_id);

-- ─── updated_at trigger ──────────────────────────────────────────────────────

create or replace function update_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger sessions_updated_at
  before update on sessions
  for each row execute function update_updated_at();

-- ─── Row Level Security ───────────────────────────────────────────────────────
-- Respondents access their session via token; admin uses service role key

alter table sessions       enable row level security;
alter table respondents    enable row level security;
alter table concepts       enable row level security;
alter table diffs          enable row level security;
alter table invite_tokens  enable row level security;

-- Service role (used server-side) bypasses RLS automatically.
-- Anon key (used client-side) gets read-only access to their own session via token.

-- Allow token-bearing clients to read their session
create policy "token holders can read session"
  on sessions for select
  using (
    exists (
      select 1 from invite_tokens
      where invite_tokens.session_id = sessions.id
        and invite_tokens.token = current_setting('request.jwt.claims', true)::json->>'token'
        and invite_tokens.expires_at > now()
    )
  );

-- Allow token-bearing clients to insert their own response
create policy "token holders can insert respondent"
  on respondents for insert
  with check (
    exists (
      select 1 from invite_tokens
      where invite_tokens.session_id = respondents.session_id
        and invite_tokens.token = current_setting('request.jwt.claims', true)::json->>'token'
        and invite_tokens.used = false
        and invite_tokens.expires_at > now()
    )
  );

-- Allow token holders to read diffs for their session
create policy "token holders can read diff"
  on diffs for select
  using (
    exists (
      select 1 from invite_tokens
      where invite_tokens.session_id = diffs.session_id
        and invite_tokens.token = current_setting('request.jwt.claims', true)::json->>'token'
        and invite_tokens.expires_at > now()
    )
  );
