// ─── Questionnaire sections (mirrors PDF structure) ─────────────────────────

export interface Answers {
  // Audience & market
  primaryAudience: string
  painPoints: string
  audienceRefs: string
  // Success metrics
  launchKpi: string
  ninetyDayKpi: string
  metricOwner: string
  // Constraints
  techConstraints: string
  budgetTimeline: string
  regulatory: string
  hardNos: string
  // Purpose
  layerPurpose: string
  successState: string
  // Narrative
  entryPoints: string[]
  journeyMap: string
  dropRisk: string
  // Components
  mustHave: string[]
  niceToHave: string
  remove: string
  // Placement & rationale
  aboveFold: string
  scrollOrder: string
  mobileDelta: string
  // References & open flags
  refSites: string
  openFlags: string
}

// ─── Respondent ──────────────────────────────────────────────────────────────

export type Layer =
  | 'Layer 1 · Brand + SEO'
  | 'Layer 2 · UX + Performance'
  | 'Layer 3 · UX + Performance + Tech'
  | 'Discovery · All contributors'

export interface Respondent {
  id: string
  sessionId: string
  name: string
  role: string
  layer: Layer
  answers: Answers
  concept: Concept | null
  submittedAt: string
}

// ─── Concept (generated by Claude) ──────────────────────────────────────────

export interface Concept {
  hero: {
    headline: string
    sub: string
    layout: string
    visual: string
    cta: string
  }
  scrollStructure: { order: number; section: string; rationale: string }[]
  visualSystem: {
    typography: { primary: string; accent: string }
    palette: { name: string; hex: string; role: string }[]
    aesthetic: string
  }
  conversionLogic: {
    aboveFoldPriority: string
    trustSignals: string
    mobileDelta: string
  }
  openTensions: string[]
  rawText: string
}

// ─── Session ─────────────────────────────────────────────────────────────────

export type SessionStatus = 'collecting' | 'ready_to_diff' | 'diffed' | 'exported_to_figma'

export interface Session {
  id: string
  projectName: string
  createdBy: string
  status: SessionStatus
  respondentCount: number
  minRespondentsForDiff: number
  createdAt: string
  updatedAt: string
}

// ─── Diff (generated by Claude across all concepts) ──────────────────────────

export interface DiffItem {
  type: 'aligned' | 'tension' | 'priority'
  text: string
  respondents?: string[]
}

export interface Diff {
  sessionId: string
  items: DiffItem[]
  generatedAt: string
  rawText: string
}

// ─── Figma export ────────────────────────────────────────────────────────────

export interface FigmaExportResult {
  fileKey: string
  pages: { name: string; nodeId: string; respondentId: string | 'synthesis' }[]
  exportedAt: string
}

// ─── API request / response shapes ───────────────────────────────────────────

export interface GenerateConceptRequest {
  respondentId: string
  sessionId: string
  answers: Answers
  name: string
  role: string
  layer: Layer
}

export interface GenerateConceptResponse {
  concept: Concept
}

export interface GenerateDiffRequest {
  sessionId: string
}

export interface GenerateDiffResponse {
  diff: Diff
}

export interface FigmaExportRequest {
  sessionId: string
}

export interface FigmaExportResponse {
  result: FigmaExportResult
}
